name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform-dev:
    name: 'Terraform - Dev'
    runs-on: ubuntu-latest
    environment: production
    env:
       ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
       ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
       ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
       ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
     
    - name: Terraform Init (Dev)
      run: terraform init
      working-directory: ./dev

    - name: Terraform Format (Dev)
      run: terraform fmt -check
      working-directory: ./dev

    - name: Terraform Plan (Dev)
      run: terraform plan 
      working-directory: ./dev

    - name: Terraform Apply (Dev)
      run: terraform apply -auto-approve 
      working-directory: ./dev

  terraform-prod:
    name: 'Terraform - Prod'
    runs-on: ubuntu-latest
    environment: production
    env:
       ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
       ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
       ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
       ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init (Prod)
      run: terraform init
      working-directory: ./prod

    - name: Terraform Format (Prod)
      run: terraform fmt -check
      working-directory: ./prod

    - name: Terraform Plan (Prod)
      run: terraform plan
      working-directory: ./prod

    - name: Terraform Apply (Prod)
      run: terraform apply -auto-approve
      working-directory: ./prod

  terraform-staging:
    name: 'Terraform - Staging'
    runs-on: ubuntu-latest
    environment: staging
    env:
       ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
       ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
       ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
       ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init (Staging)
      run: terraform init
      working-directory: ./staging

    - name: Terraform Format (Staging)
      run: terraform fmt -check
      working-directory: ./staging

    - name: Terraform Plan (Staging)
      run: terraform plan
      working-directory: ./staging

    - name: Terraform Apply (Staging)
      run: terraform apply -auto-approve
      working-directory: ./staging
